apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-pod
  template:
    metadata:
      name: backend-pod
      labels:
        app: backend-pod
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: pubsub-key
        - name: firebase-cloud-key
          secret:
            secretName: firebase-key
      containers:
        - name: backend
          image: gcr.io/{google-id}/backend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
            - name: firebase-cloud-key
              mountPath: /var/secrets/firebase
          env:
            - name: GOOGLE_PROJECT_ID
              value: { google-id }
            - name: PUBSUB_TOPIC_NAME_INPUT
              value: analyzer_input
            - name: PUBSUB_TOPIC_NAME_OUTPUT
              value: analyzer_output
            - name: PUBSUB_SUBSCRIPTION_NAME
              value: analyzer_output-sub
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: path-to-secret
            - name: FIREBASE_KEY
              value: path-to-secret
