FROM node:14.16.0-alpine3.10 as build
WORKDIR /src
ENV PATH /src/node_modules/.bin:$PATH
COPY package*.json ./
RUN yarn install
COPY . ./
RUN yarn build
# production environment
FROM nginx:stable-alpine
COPY --from=build /src/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]